export const IconTypes = {
  AlertChart: 'alert-chart',
  AlertTriangle: 'alert-triangle',
  Alert: 'alert',
  AlertCircle: 'alert-circle',
  ArrowDown: 'arrow-down',
  ArrowUp: 'arrow-up',
  CaretDown: 'caret-down',
  CaretRight: 'caret-right',
  ChevronLeft: 'chevron-left',
  ChevronRight: 'chevron-right',
  ChevronUp: 'chevron-up',
  CircleArrows: 'circle-arrows',
  CircleCaretRight: 'circle-caret-right',
  CircleClose: 'circle-close',
  Close: 'close',
  Comments: 'comments',
  Contractor: 'contractor',
  Dashboard: 'dashboard',
  Database: 'database',
  Eye: 'eye',
  EyeOff: 'eye-off',
  Fic: 'fic',
  Forward: 'forward',
  Guarantee: 'guarantee',
  Help: 'help',
  Ipoe: 'ipoe',
  Lock: 'lock',
  Monitoring: 'monitoring',
  News: 'news',
  NG: 'ng',
  Note: 'note',
  OK: 'ok',
  OperationStatus: 'operation-status',
  Order: 'order',
  QuickSetup: 'quick-setup',
  SearchData: 'search-data',
  Search: 'search',
  Sim: 'sim',
  Support: 'support',
  Terminal: 'terminal',
  TrafficStatus: 'traffic-status',
  UpRightSquare: 'up-right-square',
  Vpn: 'vpn',
} as const
export type IconType = (typeof IconTypes)[keyof typeof IconTypes]

export const NovaIconTypes = {
  AccessMobile: 'access-mobile',
  AccessSite: 'access-site',
  AlertCircle: 'alert-circle',
  AlertTriangle: 'alert-triangle',
  ArrowLeftDouble: 'arrow-left-double',
  Check: 'check',
  ChevronLeft: 'chevron-left',
  ChevronLeftDouble: 'chevron-left-double',
  ChevronRight: 'chevron-right',
  ChevronRightDouble: 'chevron-right-double',
  Clock: 'clock',
  CloseCircle: 'close-circle',
  Contract: 'contract',
  Download: 'download',
  Edr: 'edr',
  Edit: 'edit',
  EyeOff: 'eye-off',
  Eye: 'eye',
  GlobalConnect: 'global-connect',
  HelpCircle: 'help-circle',
  Help: 'help',
  Home: 'home',
  Idaas: 'idaas',
  Information: 'information',
  Interconnect: 'interconnect',
  InternetGateway: 'internet-gateway',
  LanSecurity: 'lan-security',
  Lock: 'lock',
  Maintenance: 'maintenance',
  Notification: 'notification',
  OrderHistory: 'order-history',
  RemoteAccess: 'remote-access',
  SatelliteConnect: 'satellite-connect',
  Search: 'search',
  SecuredWan: 'secured-wan',
  SortArrows: 'sort-arrows',
  SortArrowsAsc: 'sort-arrows-asc',
  SortArrowsDesc: 'sort-arrows-desc',
  SupportSpeechBubble: 'support-speech-bubble',
  UpRightSquare: 'up-right-square',
  WanSecurity: 'wan-security',
} as const
export type NovaIconType = (typeof NovaIconTypes)[keyof typeof NovaIconTypes]

export const IconSize = {
  xSmall: '8px',
  small: '12px',
  smallMiddle: '16px',
  middle: '20px',
  large: '30px',
  xLarge: '60px',
} as const
